title: oxyd.space
description: Free subdomains for everyone. Claim yourname.oxyd.space through a GitHub issue form.
url: https://oxyd.space
baseurl: ""

permalink: /:title

exclude:
  - node_modules/
  - .pre-commit-config.yaml
  - docs

keep_files:
  - assets/
  - CNAME
